name: CI/CD Pipeline - Wisecow App

on:
  push:
    branches:
      - main   # run only on main branch pushes

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/wisecow-app:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/wisecow-app:latest

  deploy:   
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      #Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      #Install kubectl
      - name: Set up Kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      #Update kubeconfig for EKS
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name wisecow-cluster --region ap-south-1

      #Create namespace if not exists
      - name: Create namespace wisecow
        run: kubectl create namespace wisecow --dry-run=client -o yaml | kubectl apply -f -

      #Deploy to EKS
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f K8s/deployment.yaml -n wisecow
          kubectl apply -f K8s/service.yaml -n wisecow
          kubectl apply -f K8s/ingress.yaml -n wisecow

